<a href="https://colab.research.google.com/github/JavZon/Takrorlash/blob/main/Customer_seg_takrorlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Customer segmentation (takroriy)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

In [11]:
url="https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/customer_segmentation.csv"
df = pd.read_csv(url)
df.head()

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0            1   41    2               6      19      0.124       1.073   
1            2   47    1              26     100      4.582       8.218   
2            3   33    2              10      57      6.111       5.802   
3            4   29    2               4      19      0.681       0.516   
4            5   47    1              31     253      9.308       8.908   

   Defaulted Address  DebtIncomeRatio  
0        0.0  NBA001              6.3  
1        0.0  NBA021             12.8  
2        1.0  NBA013             20.9  
3        0.0  NBA009              6.3  
4        0.0  NBA008              7.2

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Customer Id      850 non-null    int64  
 1   Age              850 non-null    int64  
 2   Edu              850 non-null    int64  
 3   Years Employed   850 non-null    int64  
 4   Income           850 non-null    int64  
 5   Card Debt        850 non-null    float64
 6   Other Debt       850 non-null    float64
 7   Defaulted        700 non-null    float64
 8   Address          850 non-null    object 
 9   DebtIncomeRatio  850 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 66.5+ KB


In [13]:
df.isnull().sum()

Customer Id          0
Age                  0
Edu                  0
Years Employed       0
Income               0
Card Debt            0
Other Debt           0
Defaulted          150
Address              0
DebtIncomeRatio      0
dtype: int64

In [15]:
df['Defaulted']=df['Defaulted'].fillna(0)

In [16]:
df.isnull().sum()

Customer Id        0
Age                0
Edu                0
Years Employed     0
Income             0
Card Debt          0
Other Debt         0
Defaulted          0
Address            0
DebtIncomeRatio    0
dtype: int64

As Adress column is not important, we drop this column

In [17]:
df.drop(columns='Address', inplace=True)

In [22]:
df.head(2)

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0            1   41    2               6      19      0.124       1.073   
1            2   47    1              26     100      4.582       8.218   

   Defaulted  DebtIncomeRatio  
0        0.0              6.3  
1        0.0             12.8

In [23]:
X=df.drop(columns='Customer Id').values

In [25]:
X[:1]

array([[41.   ,  2.   ,  6.   , 19.   ,  0.124,  1.073,  0.   ,  6.3  ]])

In [26]:
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [27]:
X[:1]

array([[ 0.74291541,  0.31212243, -0.37878978, -0.71845859, -0.68381116,
        -0.59048916, -0.52379654, -0.57652509]])

In [28]:
kmeans=KMeans(n_clusters=3, random_state=42, init='k-means++')
kmeans.fit(X)

KMeans(n_clusters=3, random_state=42)

In [30]:
kmeans.labels_[:10]

array([0, 2, 1, 0, 2, 2, 0, 0, 0, 2], dtype=int32)

In [31]:
kmeans.cluster_centers_

array([[-1.49558091e-01, -1.14064018e-01, -1.34481828e-01,
        -2.72413651e-01, -3.35659257e-01, -3.69866734e-01,
        -5.23796543e-01, -3.24345859e-01],
       [-3.90439547e-01,  1.62695612e-01, -6.79376729e-01,
        -3.86448408e-01, -6.83901553e-05, -6.93056978e-02,
         1.87982575e+00,  5.69270845e-01],
       [ 1.00292949e+00,  2.37745062e-01,  1.27767064e+00,
         1.45504409e+00,  1.24780477e+00,  1.45422700e+00,
        -2.04998195e-01,  5.53954880e-01]])

In [32]:
df.head(2)

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0            1   41    2               6      19      0.124       1.073   
1            2   47    1              26     100      4.582       8.218   

   Defaulted  DebtIncomeRatio  
0        0.0              6.3  
1        0.0             12.8

In [34]:
df['cluster']=kmeans.labels_

In [38]:
df.sample(2)

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
648          649   40    1               8      28      0.534       0.474   
369          370   36    1              17      54      0.727       1.649   

     Defaulted  DebtIncomeRatio  cluster  
648        0.0              3.6        0  
369        0.0              4.4        0

In [37]:
df.groupby('cluster').mean()

Customer Id        Age       Edu  Years Employed      Income  \
cluster                                                                 
0         425.302412  33.827458  1.604824        7.654917   36.181818   
1         424.451807  31.891566  1.861446        3.963855   31.789157   
2         427.434483  43.089655  1.931034       17.220690  102.724138   

         Card Debt  Other Debt  Defaulted  DebtIncomeRatio  
cluster                                                     
0         0.863681    1.822410   0.000000         7.993506  
1         1.576675    2.843355   0.987952        13.994578  
2         4.227897    8.018490   0.131034        13.891724